# Generated by Django 3.2.25 on 2024-03-10 21:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('luigis_site', '0006_alter_cartitem_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cartitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
    ]
